export const EMPLOYEE_REMOVED = 'EMPLOYEE_REMOVED';

export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';

export const EMPLOYEE_EDITED = 'EMPLOYEE_EDITED';

export const HIDE_OPEN_EMPLOYEE_LIST_BUTTON = 'HIDE_OPEN_EMPLOYEE_LIST_BUTTON';

export const HIDE_EMPLOYEE_LIST_PANEL = "HIDE_EMPLOYEE_LIST_PANEL";

export const OPEN_EDIT_PANEL = "OPEN_EDIT_PANEL";

export const OPEN_ADD_PANEL = "OPEN_ADD_PANEL";

export const EMPLOYEE_OVERLAP = "EMPLOYEE_OVERLAP";
